version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      dotnet: 8.0
    commands:
      - dotnet tool install --global dotnet-ef
      - export PATH="$PATH:$HOME/.dotnet/tools"
      - dotnet --info
  build:
    commands:
      - dotnet restore ./src/AwsEc2/AwsEc2.csproj 
      - dotnet publish ./src/AwsEc2/AwsEc2.csproj  -c Release -o ./publish
artifacts:
  base-directory: publish
  files:
    - '**/*'